### ISSUE TITLE
Error When I try to open a file from micropython device (NodeMCU esp8266)

### ISSUE THREAD

**Issue by AHardReset** [thonny/thonny#1013]
Instead of show the files in the UI, it reports in repl.

![Captura](https://user-images.githubusercontent.com/22583153/70105209-0992ae00-15f5-11ea-9a6b-446f78db105e.PNG)

This happens after first erase flash, so if I erase the flash again and upload the .bin file then Thonny wors as expected
 
Next day I try to work the issue comes again

**Comment by aivarannamaa** [comment]
I don't understand -- how did you get to MicroPython REPL after erasing the flash?

**Comment by AHardReset** [comment]
1.- Erase flash and after write-flash with the .bin file from micropython webpage
2.- Everything works as expected
3.- In future sesions I reach this problem

**Comment by aivarannamaa** [comment]
Does resetting and reconnecting your device also cure this problem?

**Comment by RobertBlackhart** [comment]
I've seen this problem happen many times in the past few days that I've been using Thonny. It seems like it is worse the more files there are to list. That is, it happens more often if I have more files stored on the device.

In order to get out of this problem, I need to cancel the dialog window, then soft-reset my device once or twice so that the ">>>" appears in the REPL. Then I can try again. It may or may not work and I might need to repeat these steps several times.

**Comment by aivarannamaa** [comment]
Thank you for the information! I'll try to reproduce it.

**Comment by RobertBlackhart** [comment]
Might be helpful too. Sometimes I see the files listed in the window and have the text in the REPL at the same time:

![image](https://user-images.githubusercontent.com/5414318/74611762-032cb200-50cd-11ea-82ae-15089976ae89.png)

In this case, I cannot open a file. If I try, it will fail (hangs forever in the open progress dialog).

**Comment by antrapoint** [comment]
I got the same issue if i had subdirs on my micropython device. 
My workaround for Thonny 3.2.6 32bit :
TOOLS -> Open Thonny programm folder ...
Open Thonny/lib/queue.py
Goto line 153 ("_**def get(self, block=True, timeout=None**_):"
Add under the docstring: **timeout = 4**
Save and restart Thonny

This works fine for me, maybe it's the same issue. Hope it help!

**Comment by aivarannamaa** [comment]
Should be fixed in 3.3 (beta)
