### ISSUE TITLE
Can not choose Chinese(简体中文) as language inRaspberry

### ISSUE THREAD

**Issue by xiaoboGideon** [thonny/thonny#1031]
<img width="356" alt="Snipaste_2019-12-21_18-02-12" src="https://user-images.githubusercontent.com/47732510/71306503-07658780-241c-11ea-9e33-55b327269eca.png">

**Comment by aivarannamaa** [comment]
Thank you for the report!

It looks like the translation file for Chinese is broken in this release. It will be fixed in the next release. 

In the meanwhile you go back to English by deleting the language configuration key. Enter following in Terminal:

```
leafpad ~/.config/Thonny/configuration.ini
```

and delete the line starting with `language =`.
