### ISSUE TITLE
Version 

### ISSUE THREAD

**Issue by fenris** [thonny/thonny#1088]
Downloaded latest thony v3.2.6 , however when I run thonny and check the version running v3.2.1 as per the attached screenshot 

![Screenshot from 2020-02-17 13-14-51](https://user-images.githubusercontent.com/405473/74625701-2cf6df00-5188-11ea-82c0-18a0f5be04b3.png)

**Comment by aivarannamaa** [comment]
Please check whether you have another Thonny under your user Python packages. Open "Tools => Manage plug-ins" and look for "thonny" in the list. Where is it installed?

**Comment by fenris** [comment]
@aivarannamaa thanks ! i just manually upgrade the Thony through that managed plug-in. 

![Screenshot from 2020-02-17 16-28-37](https://user-images.githubusercontent.com/405473/74636252-9683e700-51a2-11ea-8cf6-64f9fcba5e01.png)

**Comment by aivarannamaa** [comment]
@fenris -- I recommend you remove `~/.local/lib/python3.7/site-packages/thonny`. Try the "uninstall" button first. If this doesn't work, then remove it manuall together with related pip metadata from the site-packages dir. This way the `thonny` package from the main `site-package` becomes visible. Otherwise you'll need to upgrade the `--user` variant each time you install new Thonny version.

I don't know how Thonny package ended up there, probably because of some plug-in, which listed Thonny as dependency.
