### ISSUE TITLE
Suggestion: column markers

### ISSUE THREAD

**Issue by DancingGuy** [thonny/thonny#1297]
It would be useful to have optional vertical dash line indentation/column markers or column numbering to help with lining up code blocks. Assistant and friendly-traceback do help a lot with this but I thought extra markers are still useful on longer stretches of code. Thanks!

**Comment by aivarannamaa** [comment]
It would be nice feature indeed. I'll keep it in the TODO list, but meanwhile please check out a 3rd party plug-in which may help you: https://pypi.org/project/thonny-block-highlight/

In order to install this, go to "Tools => Manage plug-ins", search `thonny-block-highlight`, install, restart Thonny

**Comment by aivarannamaa** [comment]
Duplicate of #1078
