### ISSUE TITLE
Where are all the commands?

### ISSUE THREAD

**Issue by mostmarc** [thonny/thonny#1326]
installing esptool gives no install option. 

Thonny 3.2.7
win 10 64bit
Python 3.8.3 64bit
Tk 8.6.9

esp32
C:\Users\marcus\esptool\__pycache__>

**Comment by aivarannamaa** [comment]
Sorry, I don't understand what are you trying to do.

**Comment by mostmarc** [comment]
Thanks for the swift reply,



I have installed Thonny IDE, working but he cannot find all the tools and
or modules for ESP32. Following the instructions on Youtube video and the
PDF resources, I can’t find any suggestions for search path installation.
The device tab has no access to the menu. The debugger is also in
non-active status. Even reinstalling and upgrading to Python 3.8 and eps
amends gives no solution. The “manage plug in menu” gives no button to
activate the choice made.



Thanks in advance

Marcus

**Comment by mostmarc** [comment]
[image: image.png]
Select device tab

**Comment by mostmarc** [comment]
[image: image.png]

**Comment by aivarannamaa** [comment]
> I can’t find any suggestions for search path installation.

Sorry, I don't understand this one

> The device tab has no access to the menu. 

Do you mean there is no "Device" menu (or nothing in the "Device" menu)? Latest Thonny versions don't use it.

> The debugger is also in non-active status.

Debugger is not available for MicroPython back-end

I don't see the pictures you posted (it seems that GitHub simply drops pictures sent by e-mail)

**Comment by mostmarc** [comment]
as attachment

**Comment by aivarannamaa** [comment]
GitHub doesn't forward attachments. You need to use GitHub web interface if you want to post pictures: https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests

**Comment by mostmarc** [comment]
![thonny](https://user-images.githubusercontent.com/3598977/92341367-11393300-f0f0-11ea-81c4-19a93e370701.png)

**Comment by aivarannamaa** [comment]
Did you read the message you got from the Device menu? It says what is going on. I don't know how to explain it better. Maybe this page helps: https://github.com/thonny/thonny/wiki/MicroPython

The error "Could not ensure raw prompt" may be fixed in the beta of Thonny 3.3. I recommend you try this: https://github.com/thonny/thonny/releases/tag/v3.3.0b2

I still don't understand what do you want to do with esptool and what is the problem

**Comment by mostmarc** [comment]
https://www.youtube.com/watch?v=lvmNLuHj25o
~minute 3.30 esptool!!

**Comment by aivarannamaa** [comment]
I see -- you want to install esptool for Thonny. But what's the problem? From your screenshot I see that you have esptool in a wrong location, Thonny won't find it from there. Did you use "Tools => Manage **plug-ins**" ?

**Comment by mostmarc** [comment]
Yes that is the question, where of what are the path stelling parameters in
Thonny and how to change them? So you can synchronize the workpage and or
libs of modules.

**Comment by aivarannamaa** [comment]
Sorry, I didn't understand your last message either. What is your native language? Try asking in your native language, maybe I'll understand.

**Comment by mostmarc** [comment]
How to change the search path in Thonny? For the workspace and the module
folder.

**Comment by aivarannamaa** [comment]
If you mean PYTHONPATH, then Thonny does not provide any means for setting or changing it.

If you want to use another interpreter instead of the bundled one, then see "Run => Select interpreter"

If you are having trouble with esptool, then you could try the beta of Thonny 3.3, which includes esptool: https://github.com/thonny/thonny/releases/tag/v3.3.0b2

**Comment by mostmarc** [comment]
Looks interesting, going to try it.

Thanks in advance.
