### ISSUE TITLE
ESP32: Both REPL and WebREPL opened: unexpected text output in WebREPL

### ISSUE THREAD

**Issue by IhorNehrutsa** [thonny/thonny#1469]
When an expression is typed in REPL or in WebREPL, it calculates and prints well in the REPL, but there is  __thonny_helper.print_mgmt_value(....) text in WebREPL.
![image](https://user-images.githubusercontent.com/70886343/101340023-dded7800-3887-11eb-9ecf-cc187b91d1ba.png)

**Comment by aivarannamaa** [comment]
This is expected. Thonny adds a its own layer over MicroPython REPL in order to be able distinguish between print output and expression evaluation result. Also, it send hidden commands to REPL when you refresh the file browser or for fetching variables into Variables view (`__thonny_helper.print_mgmt_value` formats the data such that Thonny can recognize the result from those hidden commands)
