### ISSUE TITLE
"numpy" issue when installing "opencv-python" on Raspian 64 bit

### ISSUE THREAD

**Issue by Roboteer1000** [thonny/thonny#1475]
I am using an RPi-4B running on Raspian 64-bit (i.e. Linux 5.4.79-v8+ aarch64).  
The Thonny version installed is 3.3.0.  It has numpy v. 1.16.2 installed with it.  But it does not let me update to the latest version 1.19.4.  The Python version is 3.7.3.

Thus when I tried to install "opencv-python" 4.4.0.46, the installation process hit an error with the following error message:
"numpy==1.13.3; python_version=='3.6'" "numpy==1.14.5; python_version=='3.7'"
"numpy==1.17.3; python_version=='3.8'" "numpy==1.19.3; python_version=='3.9'"
failed with error code 1 in None
Process returned with code 1

Is this a Thonny issue?  or a PIP issue?
Can you help?  with much appreciation!

**Comment by aivarannamaa** [comment]
On Raspberry you are probably using system-provided numpy (`apt install python3-numpy`). Thonny does not mess with those packages. You should get compatible version with `apt install python3-opencv`.

If you need specific versions of packages, then you need to create a virtual environment and let Thonny use it instead of the default back-end. "Run => Select interpreter => Alternative Python 3 ..." lets you do both of these actions.
