### ISSUE TITLE
pip https://mirrors.tuna.tsinghua.edu.cn/help/pypi/

### ISSUE THREAD

**Issue by GreenTeaHua** [thonny/thonny#1771]
how to set other mirrors?
eg:
 pip install -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by aivarannamaa** [comment]
Thonny does not allow specifying mirrors. If you need it then you need to use pip at the command line (Tools => Open system shell. Please note that Thonny's package manager install packages with `--user` switch, so in order to get similar behavior, you need to execute `pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --user <package name>`

**Comment by aivarannamaa** [comment]
Please reopen if you have more questions or comments about this issue!
