### ISSUE TITLE
Cannot install thonny with apt on Ubuntu 21.04 (hirsute)

### ISSUE THREAD

**Issue by vonboth** [thonny/thonny#1860]
Hi!
I cannot install Thonny using apt in Ubuntu 21.04 (hirsute).

I get the message: Package "thonny" has no installation candidate

What am I missing?

**Comment by aivarannamaa** [comment]
It looks like Thonny was not included in 21.04 apt repo. I suppose it's because it was excluded from Debian testing by mistake when 20.04 was prepared.

As an alternative, you can `pip install thonny` into a virtual environment or install Python+Thonny bundle with following command

`bash <(wget -O - https://thonny.org/installer-for-linux)`

**Comment by vonboth** [comment]
Thank you for your quick answer and your help. I used Thonny in prev. Versions of Ubuntu and just didn't understand why I couldn't install it via apt on 21.04. I will use one of your suggested alternatives.
I will close this issue.
Thank you!
