### ISSUE TITLE
Error Installing PyAudio

### ISSUE THREAD

**Issue by eimearcorcoran** [thonny/thonny#1885]
I need this package to get my code to run but every time I try to install it I get an error. The latest version is supposedly suitable for the version of Thonny that I am using.

**Comment by aivarannamaa** [comment]
It's hard to help without seeing the exact error message. According to https://pypi.org/project/PyAudio/#files, there are no prebuilt wheels for Python 3.7 (which latest Thonny+Python bundles use). This means you need to have required C/C++ compiler and libraries present in your system in order to install this library.

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!
