### ISSUE TITLE
Suggestion: change color of parenthesis matching aid highlight

### ISSUE THREAD

**Issue by villares** [thonny/thonny#2014]
Parenthesis matching aid highlight color is very close to normal text editing selection highlight. 
My suggestion is to have it changed, or other implementation solution, so text selection, while a parenthesis is still not closed, becomes easier.

As it is now:

![2021-10-23_11-00](https://user-images.githubusercontent.com/3694604/138559786-ae6be75a-5e2a-4ddf-9c1c-bf9b97e957d9.png)

Simulation:

![image](https://user-images.githubusercontent.com/3694604/138559689-9370a871-2872-47ef-8e65-b286ebb55493.png)

**Comment by aivarannamaa** [comment]
I finally found time to investigate your proposal more thoroughly but I'm going to decline after all. While your proposal would make the scope of parenthesized expression more clear, it would reduce the visual clarity. I experimented with different options, but they all turned out too invasive for my taste. 

The best of these experiments involved adding more attributes to `surrounding_parens` theme attribute:

```
"surrounding_parens": {"foreground": "Blue", "font": "BoldEditorFont", "relief": "raised", "borderwidth": 1}
```

You may want to create a new theme with more pronounced matching parens using this approach. You could try also modifying the `background` attribute.
