### ISSUE TITLE
[feature suggestion] option to save file as .py when no extension provided

### ISSUE THREAD

**Issue by LovelyA72** [thonny/thonny#2077]
It will be nice to have such a feature exists since it's impossible to rename a file in CircuitPython device right now and accidentally creating a file with no extension can be a bit frustrating to deal with.
This will be an option since there will be people that want to save a file without any extension.

**Comment by aivarannamaa** [comment]
Thank you for the suggestion!

The "Rename" command is indeed missing in the file browser (#1429), but you should be able to rename currently open file via "File => Move/Rename".

Instead of automatically appending the `.py` extension, I plan to add a confirmation dialog (#1874). This way there would be less magic and no need for a new option.

**Comment by aivarannamaa** [comment]
In the upcoming Thonny 4.0, when you omit an extension, you'll get following dialog:

![image](https://user-images.githubusercontent.com/1802/151853958-93256489-0f0f-4fdd-ac8f-badb15bde1a3.png)
