### ISSUE TITLE
Where is the serial communication module for Raspberry Pi Pico?

### ISSUE THREAD

**Issue by pete-the-dev** [thonny/thonny#2105]
I am creating a javascript web app using serial web api, and I was wondering where the code for serial communication was in thonny.

**Comment by aivarannamaa** [comment]
It is not so easy to say. The short answer would be https://github.com/thonny/thonny/tree/master/thonny/plugins/micropython, but this has everything related to MicroPython.

I'm not sure you would be able to use much from Thonny, because much of the code is dependent of Thonny's peculiarities. You'll probably learn more from https://forum.micropython.org/viewtopic.php?f=16&t=8695
