### ISSUE TITLE
Information only: Thonny crashes when using a Raspberry Pi Pico with Micropython when doing I/O with timer process going

### ISSUE THREAD

**Issue by TomSullivanInUSA** [thonny/thonny#2191]
NOTE: The issue described below also occurs if the program is loaded as main.py and executed independently of Thonny. I include this since people will often start with Thonny and tend to blame Thonny. It took me considerable time to precisely determine what is going on, and thought this might help. It appears to be a problem with Micropython, the Pico, or both.

If a timer is going at 25 Hz and it does substantial work so that is occupies a significant fraction of CPU time, then doing I/O is likely to crash Thonny.

Workaround:
KillTimer()
utime.sleep(0.1)
Do some I/O
InitTimer()

where:
tim2 = Timer()
def InitTimer():
    global kptickle,tim2
    tim2.init(freq=TickFreq, mode=Timer.PERIODIC, callback=kptickle)
def KillTimer():
    global tim2
    tim2.deinit()

In this case, the timer executes every 40 ms, and the delay is 100 ms. Other timer speeds should have different appropriate delays.

**Comment by aivarannamaa** [comment]
Thank you for this information! The serial communication is indeed a fragile part of MicroPython.

Your discovery is somewhat similar to https://github.com/micropython/micropython/issues/6899

The work-around is to make sure you stop all irq-s, timers, back-end threads before your main code finishes, so that Thonny's behind the scenes management commands (querying files, globals, etc) only run without any simultaneous background processing.
