### ISSUE TITLE
[Errno 8] while installing on ubuntu 21.10 (on a raspberry pi 4b)

### ISSUE THREAD

**Issue by Graham-Sellers** [thonny/thonny#2252]
Could not install from apt so downloaded tar and tried that.
Following the install guide, I get this error 6 lines in:
[Errno 8] Exec format error: '/home/user/apps/thonny/bin/python3.10'

**Comment by aivarannamaa** [comment]
The tar-s I've published at GitHub are meant for x86 architectures, so they don't work at Raspberry Pi. 

Instead you should `apt install python3-tk` and `pip install thonny` (preferably in a virtual environment). Since Thonny 4.0 this can be achieved also via the bash-files I've published next to tar-s. The bash-files also create desktop launcher for Thonny.

**Comment by Graham-Sellers** [comment]
Ah yes, derp on my part.

Cheers
