### ISSUE TITLE
How do if fix "minipip returned with error code 1" when trying to install packages? 

### ISSUE THREAD

**Issue by DSstudent2** [thonny/thonny#2279]

**Comment by aivarannamaa** [comment]
If the package is not upip-compatible (https://docs.micropython.org/en/latest/reference/packages.html), then you can't. 

Thonny 4.0 (https://github.com/thonny/thonny/releases) uses pipkin instead of minipip and is therefore able to install more packages.

In any case, make sure the package is meant for MicroPython.
