### ISSUE TITLE
Thonny doesn't open.

### ISSUE THREAD

**Issue by Sumu3y** [thonny/thonny#2306]
client_socket.connect(IPC_FILE)
ConnectionRefusedError: [Errno 111] Connection refused
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  1960
  Current serial number in output stream:  2022

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which OS are you using? Which Thonny version? Have you used emojis in your code? Which ones?

**Comment by Sumu3y** [comment]
Linux Mint 20.3 , thonny version 3.3.13 , used emojis like 👇 and 🚨. I removed the emojis in the code. now it's working great again. thanks for the help. really love your work.

**Comment by aivarannamaa** [comment]
In this case I'm afraid I can't do anything, because the older versions of Tk (Thonny's GUI toolkit) simply doesn't play nice with emojis. Luckily the later versions are better in this regards.

If you want to continue using emojis, then you could `apt remove thonny` and install latest Thonny+Python 3.10 bundle instead: https://github.com/thonny/thonny/releases/download/v4.0.0b3/thonny-4.0.0b3.bash
