### ISSUE TITLE
Thonny doesnt like Compiz

### ISSUE THREAD

**Issue by Skilowi** [thonny/thonny#2507]
Thonny 4.0.1, installed today by pip3

Any way how to prevent those glitches from appearing? Not using Compiz isn't acceptable answer.

Video of issue + Photo of neofetch, might be useful 

https://streamable.com/rp99dg

![Photo](https://user-images.githubusercontent.com/76708049/196231497-7f4e9fd8-f5d7-4a2d-9626-8a84279ba3fc.png)

**Comment by aivarannamaa** [comment]
Thank you for the report!

Do Python's official editor -- IDLE -- run fine in your system? I'm asking, because it uses the same UI toolkit (Tk).

**Comment by Skilowi** [comment]
IDLE has also that glitch, but those beams of light are darker, and they appear rarely

**Comment by aivarannamaa** [comment]
I'm afraid this is the problem in Tk and therefore out of my reach. If you can reproduce this in a plain Tcl/Tk application (eg. [wish](https://packages.ubuntu.com/impish/wish)), then it makes sense to raise the issue in Tcl/Tk mailing list or bug tracker. Otherwise you could notify IDLE developers about the glitch (https://github.com/python/cpython/issues) and they may come up with a better answer than I can.
