### ISSUE TITLE
ESP32 and Thonny, Device is busy or does not respond,Could not interrupt current process. Please wait, try again or select Stop/Restart!

### ISSUE THREAD

**Issue by ExcaliburAvalon** [thonny/thonny#2557]
When I use arduino, I can program and open ports, and when I use thonny, I can't save the program to esp32, and it replies to me with this message
Device is busy or does not respond. Your options:

wait until it completes current work;
use Ctrl+C to interrupt current work;
reset the device and try again;
check connection properties;
make sure the device has suitable MicroPython / CircuitPython / firmware;
make sure the device is not in bootloader mode.
I tried the following method, but nothing happened.
Click on Reset button
Stop/Restart Backend OR Ctrl+F2
![image](https://user-images.githubusercontent.com/48541946/203924791-a0957f85-4ec9-4416-a19c-d5e63872d15a.png)

**Comment by ExcaliburAvalon** [comment]
Thonny ---Run---configure interpreter---interpreter---Install or update MicroPython
Choose Port and Firmware,Insatall.
When the download is complete,it's OK.

**Comment by aivarannamaa** [comment]
I assume you have found solution to your problem. Please reopen if problem persists.

**Comment by SaurabhDwivedii** [comment]
I am using ESP8266 and getting same error , tried your above solution but not working.
please help

**Comment by aivarannamaa** [comment]
@SaurabhDwivedii, can you get your MicroPython REPL with other means (Putty, tio, screen, ...) ?

**Comment by SaurabhDwivedii** [comment]
yes, when i tried putty that time not able to connect

**Comment by SaurabhDwivedii** [comment]
> 

@aivarannamaa  yes, when i tried with putty that time not able to connect

**Comment by aivarannamaa** [comment]
In this case the you should seek help at https://github.com/orgs/micropython/discussions

**Comment by rippershinoda** [comment]
Hola a todos, tenia el mismo problema con un ESP32 CAM, buscando en otros foros ya nos habían otorgado la solución
Solución: 

Hay que editar el archivo confi.ini de Thonny.

Y en la parte de [ESP32]
hay que agregar estas lineas:

dtr = False
rts = False

El archivo config.ini se edita desde Tools , Open Thonny Data Folder
Se debe editar el archivo desde antes de que se intente instalar el firmware.
Y listo, se soluciona el problema.

**Comment by desarrollador1SMI** [comment]
> Hola a todos, tenia el mismo problema con un ESP32 CAM, buscando en otros foros ya nos habían otorgado la solución Solución:
> 
> Hay que editar el archivo confi.ini de Thonny.
> 
> Y en la parte de [ESP32] hay que agregar estas lineas:
> 
> dtr = False rts = False
> 
> El archivo config.ini se edita desde Tools , Open Thonny Data Folder Se debe editar el archivo desde antes de que se intente instalar el firmware. Y listo, se soluciona el problema.

me ha funcionado esta opción. mil gracias

**Comment by Maniprogramer** [comment]
First download  micro-python flasher file you can find this flasher file in this link "http://www.micropython.org/download/" after you visit this page proceed as per your board accordingly and download any one bin file of last 4-5 latest version of your choice.

Now you need to upload this flasher file to the board that your are working with in order to flash this bin file you need a flasher app to make this process work and you can find this flasher app for windows "https://github.com/nodemcu/nodemcu-flasher" 

for mac and linux users you can find in "https://github.com/marcelstoer/nodemcu-pyflasher" and then try to upload micro python bin file to the board in my case i'am using esp8266 after done uploading the flasher file to the board 

now you can try to upload the micro python code that you've written in thonny and try to dump it to your board and this gonna work

i've done the same steps i've mentioned above and worked for me.
i hope this helps for someone.

**Comment by BhavyeNijhawan** [comment]
> Hola a todos, tenia el mismo problema con un ESP32 CAM, buscando en otros foros ya nos habían otorgado la solución Solución:
> 
> Hay que editar el archivo confi.ini de Thonny.
> 
> Y en la parte de [ESP32] hay que agregar estas lineas:
> 
> dtr = False rts = False
> 
> El archivo config.ini se edita desde Tools , Open Thonny Data Folder Se debe editar el archivo desde antes de que se intente instalar el firmware. Y listo, se soluciona el problema.

BRO YOU ARE A LIFE SAVER
EVEN THO I HAD TO GET IT TRANSLATED FROM GOOGLE
YOURS WAS THE ONLY METHOD THAT WORKED
THANK YOU SO MUCH!
