### ISSUE TITLE
Unable to open Thonny

### ISSUE THREAD

**Issue by italiancroydoner** [thonny/thonny#2597]
Hello everyone.
Time ago I installed Thonny, and for a while it ran smoothly.
Then, one day, out of the blue, I was unable to start it up.
All I got was the annoying message in the attached file.
I have uninstalled and re-installed it countless times, but to no avail: the same [error 13 Permission denied] message keeps popping up.
For a while I thought that there was some interference from other programs, such as IDLE, but the same thing kept going on whether IDLE was installed or not.
Can someone please help?

BTW, my operating system is Windows 10.

Kindest regards

Giorgio

![thonny](https://user-images.githubusercontent.com/11245396/210256832-c6fc92ef-2dcf-405e-9971-e69692ff2739.png)

**Comment by aivarannamaa** [comment]
Thank you for the report!

Please check the file mentioned in the last line of the error message. You need to enable showing hidden files in order to see the `AppData` folder. If possible, then delete the frontend.log and try launching Thonny again.

I don't know what may have happened to this file. Did you try restarting your system?

**Comment by aivarannamaa** [comment]
Please reopen if you still have this problem and have more information to add.
