### ISSUE TITLE
RP2040/Pico shell: integers starting with 0 don't print 

### ISSUE THREAD

**Issue by linalg137** [thonny/thonny#2667]
When I enter any integer starting with zero into Thonny's MicroPython REPL, it doesn't print the value:

![image](https://user-images.githubusercontent.com/68828795/220234032-76140208-da73-4bbf-ab9a-447a7c302350.png)

However, it really does have a value:
```
>>> print(04)
4
>>> 
```
Also, it works in other programs:

![image](https://user-images.githubusercontent.com/68828795/220234603-8f7bb903-349d-4b31-89cd-3064148cb46c.png)

This might have something to do with octal.

**Comment by aivarannamaa** [comment]
Thanks for the report!

This happens because Thonny's REPL doesn't use MicroPython REPL directly and therefore needs to use its own tricks for printing the value of the expression when entered into shell. In this process it uses CPython's parser and this fails as CPython doesn't allow leading zeroes like this (you need to write `0o4` instead of `04` to express octal).

I'm surprised that MicroPython and CPython differ in this respect and I recommend simply to avoid leading zeroes like this, because it would cause confusion.

**Comment by aivarannamaa** [comment]
I created a related discussion here: https://github.com/micropython/micropython/discussions/10967
