### ISSUE TITLE
are you Ukraine people?

### ISSUE THREAD

**Issue by JustQY** [thonny/thonny#2752]
what's matter Ukraine battle with you?
when usa invade Iraq，you had support Iraq？
don‘t make technology into politics，ok？

**Comment by aivarannamaa** [comment]
I don't think we need to agree on this topic. You support who you want, I'll support who I want.

**Comment by JustQY** [comment]
so，sorry，i will say fuck you，and you'r family

**Comment by parsec501** [comment]
You are a disgrace for humanity. We know that the US fucks up routinely but just because one country does something cruel does not make the cruelty of another country right. Bad + bad ≠ good. Russia is a terrorist country and you are garbling up the blood dripping from its fingers because it turns you on 🥴
