### ISSUE TITLE
Thanks for understanding.

### ISSUE THREAD

**Issue by 3469134108** [thonny/thonny#2875]
The author's project is very good, but there are some shortcomings.I don't think authors should bring their own political views and positions to open source projects. (personal views only)

**Comment by nesergen** [comment]
Agree. Politics is a dirty and dark matter, incomprehensible to ordinary people. We do not know much to draw absolutely correct conclusions.
If the author is firm in his position, then I ask you to make it possible to independently (in the settings) remove the flag of Ukraine from the interface, it is annoying.

**Comment by sosi-deadeye** [comment]
I always remove it manually. Btw. support projects, which do not show any flags.

**Comment by Moosems** [comment]
Honestly, regardless of my opinions on any conflict, I don't really feel a need for an open source project to ayate given opinions. That being said: if the owner (who I admire) wants to keep it, I will support him regardless. If you don't like seeing a flag, that's a small price to pay for such an amazing project.

**Comment by Pernat1y** [comment]
> Politics is a dirty and dark matter, incomprehensible to ordinary people. We do not know much to draw absolutely correct conclusions.
Here goes another "we are out of politics" and "we don't know all the truth" BS. That's, like, russia propaganda's bingo.

**Comment by nesergen** [comment]
> Here goes another "we are out of politics" and "we don't know all the truth" BS. That's, like, russia propaganda's bingo.

Do you really believe that only Russians know how to lie? Those. there is no propaganda in America, there is no propaganda in Europe either, and in Ukraine all the saints also speak exclusively the truth? And all the media are incorruptible and strictly observe professional etiquette? Yes, you live in a perfect world!

**Comment by OlehAhieienko** [comment]
> > Here goes another "we are out of politics" and "we don't know all the truth" BS. That's, like, russia propaganda's bingo.
> 
> Do you really believe that only Russians know how to lie? Those. there is no propaganda in America, there is no propaganda in Europe either, and in Ukraine all the saints also speak exclusively the truth? And all the media are incorruptible and strictly observe professional etiquette? Yes, you live in a perfect world!

Again, [Whataboutism](https://en.wikipedia.org/wiki/Whataboutism)

**Comment by aivarannamaa** [comment]
> there is no propaganda in Europe either, and in Ukraine all the saints also speak exclusively the truth? And all the media are incorruptible and strictly observe professional etiquette?

Are you implying that the main reason people are trying for support Ukraine, is the propaganda of "the collective west"? Not the invasion itself? Are you trying to convince me that Ukraine is not worth supporting in this situation? If not then what? Should I reword my call and replace "invasion" with "special military operation" to make it less hurtful for Russians?

**Comment by 3469134108** [comment]
> > there is no propaganda in Europe either, and in Ukraine all the saints also speak exclusively the truth? And all the media are incorruptible and strictly observe professional etiquette?
> 
> Are you implying that the main reason people are trying to support Ukraine, is the propaganda of "the collective west"? Not the invasion itself? Are you trying to convince me that Ukraine is not worth the support, because without western propaganda we would see that the invasion was justified?
> 
> If not, then what? Should I reword my call and replace "invasion" with "special military operation" to make it less hurtful for Russians?

No, I don't have those intentions. I'm a 16 pair student and I don't have any political views.

**Comment by 3469134108** [comment]
Declare again! I'm just a junior high school student. Do you really think I'm speaking up for Ukraine or Russia? No, you're wrong. This is just a suggestion. There's no political guidance content.

**Comment by gnull** [comment]
https://gist.github.com/gnull/6b8f1bf8a18667171d89618feef41fc1

In case you use NixOS, feel free to apply an overlay like this (based on the [comment](https://github.com/thonny/thonny/issues/2572#issuecomment-1358959963)). It cuts out the activist button from UI, but otherwise keeps everything the same, and as the new versions of Thonny reach NixOS repos, that will automatically apply to them too as you update. I made it for myself, thought I'd share it if someone else wanted the same.

That's the great thing about Free Software, the author does not control how it's shoved in your face, you can change any part of it, and you don't have to debate them or even care what they think. With other distros, applying the patch and maintaining it can take some energy, but NixOS makes it effortless.

A similar Fedora package is [here](https://github.com/gnull/thonny-no-propaganda-rpm), be sure to look at changes before you build it (for security reasons). The version of Thonny here is hard fixed though, I can't promise to keep it up to date, but you can do it yourself if there's changes upstream.

**Comment by nesergen** [comment]
@gnull Thanks, that is grate !
