### ISSUE TITLE
Wiki: installing Thonny and Python separately for Windows

### ISSUE THREAD

**Issue by rootsmusic** [thonny/thonny#2880]
I suggest starting the [instructions for Windows](https://github.com/thonny/thonny/wiki/Windows#installing-thonny-and-python-separately) with a Python download from the Microsoft Store, then creating a virtual environment for Thonny under that Python version.

P.S. the instructions for [SeparateInstall](https://github.com/thonny/thonny/wiki/SeparateInstall) needs to be updated, because versions [4.0.0](https://github.com/thonny/thonny/releases/tag/v4.0.0) and newer don't support Python 3.7.  (I notice that only Windows install thonnyapp, while other platforms install [thonny](https://pypi.org/project/thonny/).) #2874

**Comment by aivarannamaa** [comment]
Because of updates in `pip` (and other trends in Python packaging) it's getting harder to support packages with extra steps in the end of the installation process. Therefore I now yanked `thonnyapp` and updated Wiki accordingly https://github.com/thonny/thonny/wiki/Windows#installing-thonny-and-python-separately.

**Comment by rootsmusic** [comment]
Ok @aivarannamaa, also see #2874 for non-Windows platforms.
