### ISSUE TITLE
Bare-Arm works on putty , but does not work on thonny

### ISSUE THREAD

**Issue by lwshowl** [thonny/thonny#3047]
<img width="709" alt="image" src="https://github.com/thonny/thonny/assets/49158593/061ad2fa-4f4e-40be-943d-fec45fd68868">

thonny prints the welcome message but no input prompt is printed , and always shows the device is busy

![image](https://github.com/thonny/thonny/assets/49158593/624c22f2-f753-4a00-b250-17eb4089813f)
in putty everything is fine , and tested working with a lot of functions

i ported from bare-arm ports and run the REPL loop only in main methods where GC are not enabled
because i got compile errors using gc_helpers_generic.c , i seems not to compile arm code

code
```c

int main(int argc, char **argv) {
    // Initialise the MicroPython runtime.
    mp_stack_ctrl_init();
    mp_init();

    // Start a normal REPL; will exit when ctrl-D is entered on a blank line.
    pyexec_friendly_repl();

    mp_deinit();
    return 0;
}

// Handle uncaught exceptions (should never be reached in a correct C implementation).
void nlr_jump_fail(void *val) {
    for (;;) {
    }
}


// There is no filesystem so stat'ing returns nothing.
mp_import_stat_t mp_import_stat(const char *path) {
    return MP_IMPORT_STAT_NO_EXIST;
}

// There is no filesystem so opening a file raises an exception.
mp_lexer_t *mp_lexer_new_from_file(const char* filename) {
    mp_raise_OSError(MP_ENOENT);
}
```

**Comment by aivarannamaa** [comment]
Because of extra features, Thonny needs to do more before showing the prompt -- trying to interrupt running program, switching to raw or paste mode, setting date and time, querying MicroPython version etc. Some devices may not accept the timing of commands automatically submitted by Thonny.

Unfortunately I can't investigate this further without having the same kind of device.
