### ISSUE TITLE
Unable to deploy system wide

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#309]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/309) by Emmanuel Blindauer (Bitbucket: [blindauer](https://bitbucket.org/blindauer)
 GitHub: [blindauer](https://github.com/blindauer)
).**

----------------------------------------

Hello
It seems that the current installer doesn't work correctly when used through deployments tools (We use Altiris). the setup is designed to work with variables from the current user which is here SYSTEM. so the installation fails completely.

**Comment by ukzcoza** [comment]
It it helps anyone I have manged to deploy thonny to classrooms so that ALL USERS can use it (i.e. to c:\progam files.. not to APPDATA) as follows:-

thonny3.7.exe /VERYSILENT /SUPPRESSMSGBOXES /ALLUSERS

I then used PDQ Deploy to Deploy this, but you could use a tool like psexec to remotely execute this
