### ISSUE TITLE
PROBLEM IN THONNY'S BACK-END (class WDT) using IDE v4.1.4

### ISSUE THREAD

**Issue by PulseDoo** [thonny/thonny#3275]
Hello
I'm having trouble running the following code using a Nucleo F401RE (MicroPython v1.23.0 on 2024-06-02) and IDE version 4.1.4.

```
import pyb
import machine

green_led =  pyb.Pin('PA5', mode = pyb.Pin.OUT_PP)

#Enable watchdog timer with a timeout of 5 seconds
wdt =  machine.WDT(timeout = 5000)

sema = 0

def timer_thread(timer):
    global sema
    
    if sema == 0:
        green_led.value(not green_led.value())
        
        print("System in normal operation...")
        
        #Feed the watchdog timer to prevent it from resetting the system
        wdt.feed()

def pc13_callback(pin):
    global sema
    sema = 1
    
def main():
    global sema
    
    pyb.ExtInt('PC13', mode = pyb.ExtInt.IRQ_RISING, pull = pyb.Pin.PULL_NONE, callback = pc13_callback)
    timer1 =  pyb.Timer(1, freq = 3, mode = pyb.Timer.UP)
    #timer1 =  pyb.Timer(1, freq = 10, mode = pyb.Timer.UP) #does not work with Thonny 4.1.4, but works on v3.3.13 
    timer1.callback(timer_thread)



main()
```

The line of code that gives the problem is the following:

`timer1 =  pyb.Timer(1, freq = 10, mode = pyb.Timer.UP)`
Using Thonny IDE v4.1.4, it works only if I set the _freq_ parameter to 2 or maximum 3 Hz , while v3.3.13 is working also for freq = 10.

The first print of the "_System in normal operation..._" message is aborted and the strange message "_KeyboardInterrupt_" appears even if I do not "interact" with the keyboard (see attached screenshot).

![watchdog_timer_issue](https://github.com/user-attachments/assets/2e231fb8-6364-436a-9143-3ec8b37a5bf9)

The problem seems independent from the Micropython version, in fact I also tried a previous version (v1.19) of the FW and found the same behavior.

Thanks in advance for your feedback

My best regards

**Comment by aivarannamaa** [comment]
Serial communication with MicroPython has been rather sensitive to timing of the operations. So far such problems have been caused by bugs in the serial driver or in the communication part of MicroPython. Most likely in this case Thonny 3 wrote to the serial channel in a way that did not trigger the underlying problems. I'm afraid I can't find a timing pattern, which fits all devices on all platforms.

Thonny 5.0 will come with more advanced settings dialog for MicroPython, which allows selecting different communication methods and one of them could fix your case.

**Comment by PulseDoo** [comment]
OK...thanks a lot for the feedback, then I look forward to the release of Thonny version 5.
When is it expected?

**Comment by aivarannamaa** [comment]
I can't promise anything about Thonny 5.0. It has been hard to find time for Thonny lately.
