### ISSUE TITLE
Allow overriding default view locations (custom layout)

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#544]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/544) by me.**

----------------------------------------

**Comment by elliotwoods** [comment]
I'd love this feature also - it's the main thing that's lacking for me within the interface
I'm not sure what the best way is for Thonny to implement this. Either:

Split view (code pane can be become 2 panes each with independant tab lists)
Tabs can be freely moved around (including Shell, Files, etc)
Pop out any tab into its own window
Mix of above
I am aware that Thonny puts the word 'beginner' in its tagline, and this maybe isn't particularly a beginners feature. I find Thonny to be an excellent tool (by far the best) for MicroPython development, and it would be great to be able to use it for more advanced workflows.

Is there a strategic design reason why multiple code windows cannot be opened side-by-side within Thonny?

p.s. Thank you for this excellent excellent tool. I love it!

**Comment by aivarannamaa** [comment]
Sorry for the late reply!

In this issue I intended to allow overriding non-editor panel locations.

Displaying several editors at once never occurred to me as important (I guess I've used such feature only couple of times during my career).

At the moment I'm hesitant about implementing it, because it would make both Thonny's code and UI more complex. Can you give me an example use case where you would need this feature?

**Comment by elliotwoods** [comment]
I generally always have 2-3 code panes open (it's perhaps a hangover from working in C++, and since other editors support it I guess I'm not alone)
That said, I certainly don't intend to convince anybody that this is a way that they should work if they think otherwise!

Example case for me:
- I'm implementing 2 or more classes which strongly inter-relate (e.g. Encoder, Motor, Servo classes)
- I'm implementing a class in one window, and have a test script for that class in another window
- I'm writing a class that implements a base class, and want to see the base class for reference whilst implementing the child class
- I'm moving functionality from one class/module to another
- I am messy and like to cover my screen in busy text ;)

These examples might not be particularly 'pythonic' ?

**Comment by aivarannamaa** [comment]
Thank you! Most of these look like pretty good reasons.

Most likely I'll keep current editor pane as it is, but I'll consider adding the possibility to create a secondary "mirror" pane which can be tied to a editor in the editor pane.

**Comment by elliotwoods** [comment]
Thank you for considering this use case - i look forward to some possible multi-window features in the future.
Again, Thonny is really great. Really appreciate all your work!

**Comment by aivarannamaa** [comment]
Workaround: https://github.com/thonny/thonny/wiki/Custom-layout
