### ISSUE TITLE
Tab to space replacement on paste can alter strings

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#656]
From https://bitbucket.org/plas/thonny/issues/edit/647:

#548  is awesome and I love it BUT:

If one copies in something containing tabs in other places than code formatting whitespace, such as strings, it will also replace those. This should not happen.

Please make sure that the replacement only affects tabs at the beginnings of lines or tabs in lines where there is nothing but spaces in front.

Consider this code:

```
#!python

tsv = "1	a	!"  # separated by tabs!
fields = tsv.split("\t")
assert len(fields) == 3
```

**Comment by lurch** [comment]
> Please make sure that the replacement only affects tabs at the beginnings of lines or tabs in lines where there is nothing but spaces in front.

IMHO that'd be too simple of an approach - remember that strings can be multi-line too! Also, if you've got code that you've got commented out with a `#` at the start of the line, you'd probably also want that (commented-out) indentation to get converted to spaces? Otherwise you'd get mixed indentation when un-commenting the previously-commented lines.

I think the way to "fix this" would be to parse the Python input into "stuff inside a string" (`'single-quoted'`, `"double-quoted"` and the `'''triple-quote'''` `"""versions of those"""`) and "everything else", and only do the tab-to-space conversion in the "everything else" part?

> I noticed it when preparing an example of csv/tsv for students to parse.

Perhaps the tab-to-space conversion should only be done for "*.py" files? As well as TSV files, you wouldn't want tabs to be replaced with spaces if using Thonny to edit a Makefile :wink:  Obviously Thonny should assume that new files are Python until they're saved with an explicit filename.

**Comment by aivarannamaa** [comment]
Tab to space replacement is no more
