### ISSUE TITLE
The code text popup menu will disappeared when I click  the mouse right button.

### ISSUE THREAD

**Issue by noval102200** [thonny/thonny#713]
this problem happen on linux os.
if use clean dark ui theme.when I click  the mouse right button,The code text popup menu will disappeared immediately every time.

**Comment by chpurdy** [comment]
I think it's by design.  Hold down the right mouse button and release it on your choice.  

On a side note, I just spent the past 2 hours trying to find a way to get the menu to stay up, but no luck with tk_popup.  Using post it will stay up, but I haven't figured out how to get the menu to go away without making a selection.

**Comment by aivarannamaa** [comment]
Thank you for the report! This seems to be related to #731
