### ISSUE TITLE
Won't load large python script

### ISSUE THREAD

**Issue by Gordon999** [thonny/thonny#800]
My script is about 5900 lines, loads OK with IDLE etc but Thonny won't load it, just hangs.

Script available here as a zip...
https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=45246&p=1443213&hilit=astrophotography#p1282884

**Comment by Gordon999** [comment]
Just found out it eventually loads BUT takes ages.

**Comment by Gordon999** [comment]
and after shutting Thonny down and rebooting my PI4 Thonny now won't run from the menu.

**Comment by aivarannamaa** [comment]
Thanks for pushing me! :)

I originally did not care about performance with large files, because Thonny was meant for absolute beginners, who wouldn't write programs larger than 100 lines. Now when it's promoted as the main Python editor on RPi, I need to deal with it.

Probably the main bottleneck is syntax coloring, which is more simplistic than IDLE's. I now found some ways to optimize it (by colorizing incrementally only the visible lines).

I can't promise Thonny will be usable for 5000 line programs on RPi, but you can expect noticeable performance improvements in the next version.

**Comment by aivarannamaa** [comment]
I've made good progress -- your script now loads in 7 seconds on my RPi 3B+ and can be edited almost smoothly (except for entering/deleting parens, quotes and `#`, as these invoke heavier coloring and paren-matching processes). You will get better performance if you switch off "Highlight parentheses" from Tools => Options => Editor.

I'm stopping here (for now), because I expect large majority of Thonny users to edit modules well under 1000 lines.

**Comment by aivarannamaa** [comment]
> I'm stopping here [...]

Well, I couldn't :)

Your script now loads in couple of seconds and can be edited smoothly if no breakpoints are set. The only hiccups will be starting and closing multiline strings.

**Comment by Gordon999** [comment]
Thanks. Much appreciated.
