### ISSUE TITLE
Thonny opens micropython script in one line

### ISSUE THREAD

**Issue by stekicar** [thonny/thonny#939]
![Thonny](https://user-images.githubusercontent.com/45110503/66617054-5df35180-eba1-11e9-84de-9fd5e0875b94.png)

I open script from esp32 and it does not show correctly. What can be the cause for this?

**Comment by stekicar** [comment]
What I have noticed is that if I save file in uPyCraft, Thonny opens same file in one line as shown. Maybe, the problem is with uPyCraft?

**Comment by aivarannamaa** [comment]
Thanks for reporting this! I'll try to reproduce this and then I'll can say more

**Comment by aivarannamaa** [comment]
I could reproduce this. The problem is indeed with uPyCraft -- at least in Windows it inserts uses only carriage returns for breaking lines. Such line break was used in ancient Macs and Tk-based editor in Thonny does not treat it as a line break.

I'll add a translation from CR to CR+LF or just LF so that people coming from uPyCraft can experience proper linebreaks in Thonny.
