### ISSUE TITLE
run a multiprocess program without `self.join()` twice, will get an exception.

### ISSUE THREAD

**Issue by rnLIKEm** [thonny/thonny#963]
see the picture below
![image](https://user-images.githubusercontent.com/52340898/67621835-3f9a8080-f846-11e9-9783-2fc2a6ebab56.png)
the code below:
```
# coding:utf-8
from multiprocessing import Process

def foo():
    pass

if __name__ == '__main__':
    p = Process(target=foo, )
    p.start()
    print('End')
```

**Comment by aivarannamaa** [comment]
Reminder for myself: At the moment I don't know how to fix it. Each time a script is run, Thonny starts a new python subprocess. It looks like something is not cleaned up fast enough -- when I add a sleep(0.1) before starting new subprocess, everything runs fine (sleep(0.01) is not enough). I don't want to solve it with this hack, because it would slow down the programs which are not using multiprocessing, and it's not guaranteed that 0.1 seconds is always enough.

**Comment by rnLIKEm** [comment]
did you noticed when a subprocess run over,it will not dead?
it seems that after call it ,it will dead.I have made some pictures,see:
![1](https://user-images.githubusercontent.com/52340898/68538194-44fddc00-03ab-11ea-923a-6dfd5ae9cd65.png)
![2](https://user-images.githubusercontent.com/52340898/68538196-4b8c5380-03ab-11ea-9b18-776c361101e1.png)
![3](https://user-images.githubusercontent.com/52340898/68538198-4fb87100-03ab-11ea-8791-efd48356fc3e.png)
![4](https://user-images.githubusercontent.com/52340898/68538200-5515bb80-03ab-11ea-9b40-23218aa7ce4c.png)

**Comment by aivarannamaa** [comment]
This matches with my tests -- it looks like a process remains alive after main thread finishes.

**Comment by rnLIKEm** [comment]
it's seems that which is waitting for something.
maybe it's waitting for me to enter `p` in the shell then press `enter`
