### ISSUE TITLE
Assistant File Reference Error

### ISSUE THREAD

**Issue by KPTousey** [thonny/thonny#994]
The assistant references a previous python file and indicates "possibly bad file name" when the file is no longer in session.

**Comment by aivarannamaa** [comment]
Is your current directory still the one containing the possibly bad file name? If yes, then the warning is warranted, because you still may import it inadvertently from other scripts in the same directory.

What's the name of the problematic script in your case? It may be necessary to narrow the definition of possibly bad file name.

**Comment by aivarannamaa** [comment]
Closing for now. Please reopen if you think it should be fixed.
